
\restrict RrJauCdQmhiUhVVjwomlUCcAXSRRQ8dwkKwYQsRN8fhIGmcmq8eYULb8ndXsceh

SELECT pg_catalog.set_config('search_path', '', false);

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.keywords (
    id integer NOT NULL,
    user_id uuid NOT NULL,
    keyword text NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    filters jsonb DEFAULT '{}'::jsonb NOT NULL
);

CREATE SEQUENCE public.keywords_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.keywords_id_seq OWNED BY public.keywords.id;

CREATE TABLE public.matches (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    keyword_id integer,
    source text NOT NULL,
    hash text NOT NULL,
    notified_at timestamp with time zone,
    data jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE SEQUENCE public.matches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.matches_id_seq OWNED BY public.matches.id;

CREATE TABLE public.users (
    id uuid NOT NULL,
    email text NOT NULL,
    name text,
    avatar text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.keywords ALTER COLUMN id SET DEFAULT nextval('public.keywords_id_seq'::regclass);

ALTER TABLE ONLY public.matches ALTER COLUMN id SET DEFAULT nextval('public.matches_id_seq'::regclass);

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.keywords
    ADD CONSTRAINT keywords_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

CREATE INDEX idx_keywords_keyword_lower ON public.keywords USING btree (lower(keyword));

CREATE INDEX idx_keywords_user_id ON public.keywords USING btree (user_id);

CREATE UNIQUE INDEX idx_keywords_user_keyword ON public.keywords USING btree (user_id, lower(keyword));

CREATE INDEX idx_matches_created_at ON public.matches USING btree (created_at);

CREATE UNIQUE INDEX idx_matches_hash ON public.matches USING btree (hash);

CREATE INDEX idx_matches_source ON public.matches USING btree (source);

CREATE INDEX idx_matches_user_notified_at ON public.matches USING btree (user_id, notified_at);

ALTER TABLE ONLY public.keywords
    ADD CONSTRAINT keywords_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_keyword_id_fkey FOREIGN KEY (keyword_id) REFERENCES public.keywords(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

\unrestrict RrJauCdQmhiUhVVjwomlUCcAXSRRQ8dwkKwYQsRN8fhIGmcmq8eYULb8ndXsceh

